title: Mihir Kavishwar 
author:
  name: Mihir Kavishwar
  email: mihirk@iitb.ac.in
description: > # this means to ignore newlines until "show_excerpts:"
  Work in progress 

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: dark

  # generate social links in footer
  social_links:
    twitter: https://twitter.com/mihirk_394
    github:  https://github.com/mihirvk
    # devto: jekyll
    # dribbble: jekyll
    facebook: https://www.facebook.com/mihir.kavishwar710/
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: https://www.linkedin.com/in/mihir-kavishwar-862349188/
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
